/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AgentSignupRouteImport } from './routes/agent-signup'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AgentEnquiriesRouteImport } from './routes/agent/enquiries'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as AgentOnboardingRouteImport } from './routes/agent/onboarding'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin/reviews/index'
import { Route as AdminPropertiesIndexRouteImport } from './routes/admin/properties/index'
import { Route as AdminLocationsIndexRouteImport } from './routes/admin/locations/index'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin/inquiries/index'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin/inquiries/$id'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin/agents/index'
import { Route as AdminAgentsVerificationRouteImport } from './routes/admin/agents/verification'
import { Route as AdminPropertiesNewRouteImport } from './routes/admin/properties/_new'
import { Route as AdminPropertiesIdRouteImport } from './routes/admin/properties/$id'
import { Route as AdminAgentsNewRouteImport } from './routes/admin/agents/_new'
import { Route as AdminMarketingVideosIndexRouteImport } from './routes/admin/marketing/videos/index'
import { Route as AdminMarketingAssetsIndexRouteImport } from './routes/admin/marketing/assets/index'
import { Route as AdminMarketingVideosNewRouteImport } from './routes/admin/marketing/videos/_new'
import { Route as AdminMarketingAssetsNewRouteImport } from './routes/admin/marketing/assets/_new'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSignupRoute = AgentSignupRouteImport.update({
  id: '/agent-signup',
  path: '/agent-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewsRoute,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentOnboardingRoute = AgentOnboardingRouteImport.update({
  id: '/agent/onboarding',
  path: '/agent/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesIndexRoute = AdminPropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsIndexRoute = AdminLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesNewRoute = AdminPropertiesNewRouteImport.update({
  id: '/properties/_new',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesIdRoute = AdminPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsNewRoute = AdminAgentsNewRouteImport.update({
  id: '/agents/_new',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingVideosIndexRoute =
  AdminMarketingVideosIndexRouteImport.update({
    id: '/marketing/videos/',
    path: '/marketing/videos/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingAssetsIndexRoute =
  AdminMarketingAssetsIndexRouteImport.update({
    id: '/marketing/assets/',
    path: '/marketing/assets/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingVideosNewRoute = AdminMarketingVideosNewRouteImport.update({
  id: '/marketing/videos/_new',
  path: '/marketing/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingAssetsNewRoute = AdminMarketingAssetsNewRouteImport.update({
  id: '/marketing/assets/_new',
  path: '/marketing/assets',
  getParentRoute: () => AdminRoute,
} as any)

// ── New routes added in Part 3 ──────────────────────────────────────────────
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentEnquiriesRoute = AgentEnquiriesRouteImport.update({
  id: '/agent/enquiries',
  path: '/agent/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsVerificationRoute = AdminAgentsVerificationRouteImport.update({
  id: '/agents/verification',
  path: '/agents/verification',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent-signup': typeof AgentSignupRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/join': typeof JoinRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/agent/enquiries': typeof AgentEnquiriesRoute
  '/agent/onboarding': typeof AgentOnboardingRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/admin/agents': typeof AdminAgentsNewRoute
  '/admin/agents/verification': typeof AdminAgentsVerificationRoute
  '/admin/properties/$id': typeof AdminPropertiesIdRoute
  '/admin/properties': typeof AdminPropertiesNewRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/marketing/assets': typeof AdminMarketingAssetsNewRoute
  '/admin/marketing/videos': typeof AdminMarketingVideosNewRoute
  '/admin/marketing/assets/': typeof AdminMarketingAssetsIndexRoute
  '/admin/marketing/videos/': typeof AdminMarketingVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agent-signup': typeof AgentSignupRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/agent/onboarding': typeof AgentOnboardingRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/properties/$id': typeof AdminPropertiesIdRoute
  '/admin/properties': typeof AdminPropertiesIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/locations': typeof AdminLocationsIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/marketing/assets': typeof AdminMarketingAssetsIndexRoute
  '/admin/marketing/videos': typeof AdminMarketingVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent-signup': typeof AgentSignupRoute
  '/agents': typeof AgentsRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/properties': typeof PropertiesRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/agent/onboarding': typeof AgentOnboardingRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/property/$slug': typeof PropertySlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/admin/agents/_new': typeof AdminAgentsNewRoute
  '/admin/properties/$id': typeof AdminPropertiesIdRoute
  '/admin/properties/_new': typeof AdminPropertiesNewRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/locations/': typeof AdminLocationsIndexRoute
  '/admin/properties/': typeof AdminPropertiesIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/marketing/assets/_new': typeof AdminMarketingAssetsNewRoute
  '/admin/marketing/videos/_new': typeof AdminMarketingVideosNewRoute
  '/admin/marketing/assets/': typeof AdminMarketingAssetsIndexRoute
  '/admin/marketing/videos/': typeof AdminMarketingVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent-signup'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/properties'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/agent/onboarding'
    | '/agents/$slug'
    | '/blog/$slug'
    | '/property/$slug'
    | '/reviews/$slug'
    | '/admin/'
    | '/agent/'
    | '/admin/agents'
    | '/admin/properties/$id'
    | '/admin/properties'
    | '/admin/agents/'
    | '/admin/blog/'
    | '/admin/inquiries/'
    | '/admin/locations/'
    | '/admin/properties/'
    | '/admin/reviews/'
    | '/admin/settings/'
    | '/admin/marketing/assets'
    | '/admin/marketing/videos'
    | '/admin/marketing/assets/'
    | '/admin/marketing/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agent-signup'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/properties'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/agent/onboarding'
    | '/agents/$slug'
    | '/blog/$slug'
    | '/property/$slug'
    | '/reviews/$slug'
    | '/admin'
    | '/agent'
    | '/admin/agents'
    | '/admin/properties/$id'
    | '/admin/properties'
    | '/admin/blog'
    | '/admin/inquiries'
    | '/admin/locations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/marketing/assets'
    | '/admin/marketing/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent-signup'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/properties'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/agent/onboarding'
    | '/agents/$slug'
    | '/blog/$slug'
    | '/property/$slug'
    | '/reviews/$slug'
    | '/admin/'
    | '/agent/'
    | '/admin/agents/_new'
    | '/admin/properties/$id'
    | '/admin/properties/_new'
    | '/admin/agents/'
    | '/admin/blog/'
    | '/admin/inquiries/'
    | '/admin/locations/'
    | '/admin/properties/'
    | '/admin/reviews/'
    | '/admin/settings/'
    | '/admin/marketing/assets/_new'
    | '/admin/marketing/videos/_new'
    | '/admin/marketing/assets/'
    | '/admin/marketing/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentSignupRoute: typeof AgentSignupRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  PropertiesRoute: typeof PropertiesRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  AgentOnboardingRoute: typeof AgentOnboardingRoute
  PropertySlugRoute: typeof PropertySlugRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-signup': {
      id: '/agent-signup'
      path: '/agent-signup'
      fullPath: '/agent-signup'
      preLoaderRoute: typeof AgentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agent/onboarding': {
      id: '/agent/onboarding'
      path: '/agent/onboarding'
      fullPath: '/agent/onboarding'
      preLoaderRoute: typeof AgentOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties/': {
      id: '/admin/properties/'
      path: '/properties'
      fullPath: '/admin/properties/'
      preLoaderRoute: typeof AdminPropertiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations/': {
      id: '/admin/locations/'
      path: '/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof AdminLocationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties/_new': {
      id: '/admin/properties/_new'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties/$id': {
      id: '/admin/properties/$id'
      path: '/properties/$id'
      fullPath: '/admin/properties/$id'
      preLoaderRoute: typeof AdminPropertiesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/_new': {
      id: '/admin/agents/_new'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/videos/': {
      id: '/admin/marketing/videos/'
      path: '/marketing/videos'
      fullPath: '/admin/marketing/videos/'
      preLoaderRoute: typeof AdminMarketingVideosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/assets/': {
      id: '/admin/marketing/assets/'
      path: '/marketing/assets'
      fullPath: '/admin/marketing/assets/'
      preLoaderRoute: typeof AdminMarketingAssetsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/videos/_new': {
      id: '/admin/marketing/videos/_new'
      path: '/marketing/videos'
      fullPath: '/admin/marketing/videos'
      preLoaderRoute: typeof AdminMarketingVideosNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing/assets/_new': {
      id: '/admin/marketing/assets/_new'
      path: '/marketing/assets'
      fullPath: '/admin/marketing/assets'
      preLoaderRoute: typeof AdminMarketingAssetsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentsNewRoute: typeof AdminAgentsNewRoute
  AdminPropertiesIdRoute: typeof AdminPropertiesIdRoute
  AdminPropertiesNewRoute: typeof AdminPropertiesNewRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminLocationsIndexRoute: typeof AdminLocationsIndexRoute
  AdminPropertiesIndexRoute: typeof AdminPropertiesIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminMarketingAssetsNewRoute: typeof AdminMarketingAssetsNewRoute
  AdminMarketingVideosNewRoute: typeof AdminMarketingVideosNewRoute
  AdminMarketingAssetsIndexRoute: typeof AdminMarketingAssetsIndexRoute
  AdminMarketingVideosIndexRoute: typeof AdminMarketingVideosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentsNewRoute: AdminAgentsNewRoute,
  AdminPropertiesIdRoute: AdminPropertiesIdRoute,
  AdminPropertiesNewRoute: AdminPropertiesNewRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminLocationsIndexRoute: AdminLocationsIndexRoute,
  AdminPropertiesIndexRoute: AdminPropertiesIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminMarketingAssetsNewRoute: AdminMarketingAssetsNewRoute,
  AdminMarketingVideosNewRoute: AdminMarketingVideosNewRoute,
  AdminMarketingAssetsIndexRoute: AdminMarketingAssetsIndexRoute,
  AdminMarketingVideosIndexRoute: AdminMarketingVideosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentsRouteChildren {
  AgentsSlugRoute: typeof AgentsSlugRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsSlugRoute: AgentsSlugRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ReviewsRouteChildren {
  ReviewsSlugRoute: typeof ReviewsSlugRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsSlugRoute: ReviewsSlugRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentSignupRoute: AgentSignupRoute,
  AgentsRoute: AgentsRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  PropertiesRoute: PropertiesRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  AgentOnboardingRoute: AgentOnboardingRoute,
  PropertySlugRoute: PropertySlugRoute,
  AgentIndexRoute: AgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
